version: '3'
services:
  proxy-tor:
    build: ./proxy
    volumes:
      - ./proxy:/usr/src/app
    ports:
      - 9050:9050
      - 9051:9051
    networks:
      - default
  web-api:
    build: ./web_api
    volumes:
      - ./web_api:/usr/src/app
    ports:
      - 3001:3001
    networks:
      - default
  front-end:
    build: ./front_end
    ports:
      - 3000:3000